/**
 * NHIA (National Health Insurance Authority) Accredited HMO Directory.
 * Official directory of accredited Health Maintenance Organizations in Nigeria.
 * Deduplicated master list with 93 unique accredited organizations.
 */
export const NHIA_ACCREDITED_HMOS: string[] = [
  "A&M Healthcare Trust Limited",
  "AIICO Multishield Nigeria Limited",
  "Alleanza Health Management Limited",
  "Ally Healthcare Limited",
  "Aman Health Maintenance Organizations",
  "Anchor HMO International Company Limited",
  "Ashmed Integrated Health Services Ltd.",
  "Aspire HMO Limited",
  "Avon Healthcare Limited",
  "AXA Mansard Health Limited",
  "Bastion Health Limited",
  "Bonitas Health Maintenance Limited",
  "Century Medicaid Services Limited",
  "Clearline International Limited",
  "Crown Jewel HMO Ltd.",
  "Defence Health Maintenance Limited",
  "Delog Medical Services Ltd. (HMO)",
  "Doheec International Healthcare Limited HMO",
  "DOT HMO Ltd.",
  "Fountain Healthcare Limited",
  "GNI Healthcare Ltd",
  "Gorah Healthcare Ltd.",
  "Greenbay Healthcare Services Limited",
  "Greenfield Health Management Ltd",
  "Grooming Health Management Limited",
  "Hallmark Health Services Limited",
  "Health Assur Limited",
  "Healthcare International Limited",
  "Healthnomics HMO PLC",
  "Health Partners Limited",
  "Healthspring HMO",
  "Hopewell Healthcare Management Ltd",
  "Hygeia HMO Limited",
  "HYSSOP Health International Limited (HMO)",
  "Infinite X2 Health Maintenance Services",
  "Integrated Healthcare",
  "International Health Mgt. Services",
  "Ives Medicare",
  "Kennedia HMO Limited",
  "Leadway Health Limited",
  "Life Action Plus Ltd.",
  "Lifesaver Healthcare Limited",
  "Life Worth Medicare Ltd",
  "Maayoit Health Care Limited",
  "Marina Medical Services HMO Limited",
  "Markfema Nigeria Ltd.",
  "Masslife Healthcare Limited",
  "MB & O Healthcare Services Limited",
  "Medexia Limited",
  "Medicare Alliance Limited",
  "Mediplan Healthcare Limited",
  "Metrohealth HMO Limited",
  "Mitera Health Limited",
  "NEM Health Limited",
  "NNPC-HMO Limited",
  "Nonsuch Medicare Limited",
  "Noor Health Ltd.",
  "Novo Health Africa Limited",
  "Oceanic Health Management Limited",
  "Peramare Health Management Company Limited",
  "Phillips Health Management Services Limited",
  "Police Health Maintenance Limited",
  "Precious Healthcare Limited",
  "Prepaid Medicare Services Ltd.",
  "Princeton Health",
  "ProHealth HMO Ltd",
  "Quest Medicare Limited",
  "Redcare Health Services Limited",
  "Regenix Health Care Service Limited",
  "Reliance HMO Limited",
  "Roding Healthcare Ltd.",
  "Ronsberger Nigeria Ltd.",
  "Rothauge Healthcare Limited",
  "Royal Health Maintenance Services Ltd.",
  "Salus Trust GTE",
  "Seraph HMO Limited",
  "Skyda Health Limited",
  "Smathealth Medicare Limited",
  "Songhai Health Trust",
  "Springtide Healthcare Services Ltd.",
  "Sterling Health Managed Care Services Limited",
  "Sunu Health Nigeria Limited",
  "Synergy Wellcare Medicaid Limited",
  "Total Health Trust Limited",
  "Ultimate Health Management Services Ltd",
  "United Comprehensive Health Managers Ltd.",
  "United Healthcare International Limited",
  "Venus Medicare Ltd",
  "Veritas Healthcare Limited",
  "Well Health Network Limited",
  "Wellness Health Management Services Limited",
  "Zenor Healthcare Ltd.",
  "Zuma Health Trust",
];

export const POPULAR_HMOS = [
  "Reliance HMO Limited",
  "Hygeia HMO Limited",
  "AXA Mansard Health Limited",
  "Leadway Health Limited",
  "Avon Healthcare Limited",
  "Hallmark Health Services Limited",
  "Redcare Health Services Limited",
  "Total Health Trust Limited",
];
